dist: trusty
sudo: false
language: node_js

node_js:
  - '10'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      script:
        - npm run lint
        - npm run test:app:ci
        - npm run test:lib:ci
        - npm run coveralls
    - stage: build
      script:
        - npm run build:lib
        - cp README.md dist/ngx-plyr
        - cp LICENSE.md dist/ngx-plyr
        - npm run build:app
        - cp dist/ngx-plyr-app/index.html dist/ngx-plyr-app/404.html
    - stage: deploy
      script:
        - npx semantic-release
      deploy:
        - provider: pages
          local-dir: dist/ngx-plyr-app
          skip-cleanup: true
          github-token: $GH_TOKEN
          keep-history: true
          on:
            branch: master
